import os

files = [
    ".github/workflows/ci.yml",
    ".github/workflows/deploy-server.yml",
    ".github/workflows/deploy-web.yml",
    ".github/workflows/deploy-mobile.yml",
    ".github/workflows/db-migrate.yml",
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/ISSUE_TEMPLATE/bug_report.md",
    ".github/ISSUE_TEMPLATE/feature_request.md",
    ".github/CODEOWNERS",
    
    "apps/mobile/app/_layout.tsx",
    "apps/mobile/app/+not-found.tsx",
    "apps/mobile/app/(auth)/_layout.tsx",
    "apps/mobile/app/(auth)/login.tsx",
    "apps/mobile/app/(auth)/forgot-password.tsx",
    "apps/mobile/app/(protected)/_layout.tsx",
    "apps/mobile/app/(protected)/(tabs)/_layout.tsx",
    "apps/mobile/app/(protected)/(tabs)/index.tsx",
    "apps/mobile/app/(protected)/(tabs)/actions.tsx",
    "apps/mobile/app/(protected)/(tabs)/insights.tsx",
    "apps/mobile/app/(protected)/(tabs)/settings.tsx",
    "apps/mobile/app/(protected)/screens/homework/index.tsx",
    "apps/mobile/app/(protected)/screens/homework/[id].tsx",
    "apps/mobile/app/(protected)/screens/attendance/index.tsx",
    "apps/mobile/app/(protected)/screens/timetable/index.tsx",
    "apps/mobile/app/(protected)/screens/assignments/index.tsx",
    "apps/mobile/app/(protected)/screens/assignments/[id].tsx",
    "apps/mobile/app/(protected)/screens/fees/index.tsx",
    "apps/mobile/app/(protected)/screens/fees/receipt/[id].tsx",
    "apps/mobile/app/(protected)/screens/exam-report/index.tsx",
    "apps/mobile/app/(protected)/screens/exam-report/[id].tsx",
    "apps/mobile/app/(protected)/screens/gate-logs/index.tsx",
    "apps/mobile/app/(protected)/screens/meetings/index.tsx",
    "apps/mobile/app/(protected)/screens/applications/index.tsx",
    "apps/mobile/app/(protected)/screens/applications/new.tsx",
    "apps/mobile/app/(protected)/screens/announcements/index.tsx",
    "apps/mobile/app/(protected)/screens/announcements/[id].tsx",
    "apps/mobile/app/(protected)/screens/course-activity/index.tsx",
    "apps/mobile/app/(protected)/screens/profile/index.tsx",
    "apps/mobile/app/(protected)/screens/profile/change-password.tsx",
    "apps/mobile/app/(protected)/ai-insights/index.tsx",
    "apps/mobile/app/(protected)/ai-insights/performance.tsx",
    "apps/mobile/app/(protected)/ai-insights/attendance.tsx",
    "apps/mobile/app/(protected)/ai-insights/subject-tips.tsx",
    
    "apps/mobile/components/ui/Button.tsx",
    "apps/mobile/components/ui/Card.tsx",
    "apps/mobile/components/ui/Badge.tsx",
    "apps/mobile/components/ui/Skeleton.tsx",
    "apps/mobile/components/ui/EmptyState.tsx",
    "apps/mobile/components/ui/ErrorBoundary.tsx",
    "apps/mobile/components/ui/RefreshControl.tsx",
    "apps/mobile/components/ui/Avatar.tsx",
    "apps/mobile/components/ui/Divider.tsx",
    "apps/mobile/components/ui/Input.tsx",
    "apps/mobile/components/ui/BottomSheet.tsx",
    "apps/mobile/components/ui/Toast.tsx",
    
    "apps/mobile/components/dashboard/StudentCard.tsx",
    "apps/mobile/components/dashboard/TodayOverview.tsx",
    "apps/mobile/components/dashboard/PendingSection.tsx",
    "apps/mobile/components/dashboard/AnnouncementPreview.tsx",
    "apps/mobile/components/dashboard/AIInsightBanner.tsx",
    
    "apps/mobile/components/ai/InsightCard.tsx",
    "apps/mobile/components/ai/PerformanceTrendChart.tsx",
    "apps/mobile/components/ai/AttendanceRiskBadge.tsx",
    "apps/mobile/components/ai/SubjectRadarChart.tsx",
    "apps/mobile/components/ai/PredictedGradeCard.tsx",
    "apps/mobile/components/ai/WeeklyProgressRing.tsx",
    
    "apps/mobile/components/attendance/AttendanceCalendar.tsx",
    "apps/mobile/components/attendance/AttendanceSummary.tsx",
    "apps/mobile/components/homework/HomeworkItem.tsx",
    "apps/mobile/components/homework/HomeworkStatusBadge.tsx",
    "apps/mobile/components/fees/FeeCard.tsx",
    "apps/mobile/components/fees/PaymentHistory.tsx",
    "apps/mobile/components/exam/ExamResultCard.tsx",
    "apps/mobile/components/exam/GradeBadge.tsx",
    
    "apps/mobile/hooks/useAuth.ts",
    "apps/mobile/hooks/useStudent.ts",
    "apps/mobile/hooks/useAttendance.ts",
    "apps/mobile/hooks/useHomework.ts",
    "apps/mobile/hooks/useFees.ts",
    "apps/mobile/hooks/useExams.ts",
    "apps/mobile/hooks/useAnnouncements.ts",
    "apps/mobile/hooks/usePullToRefresh.ts",
    "apps/mobile/hooks/useOfflineSync.ts",
    "apps/mobile/hooks/useAIInsights.ts",
    
    "apps/mobile/store/authStore.ts",
    "apps/mobile/store/studentStore.ts",
    "apps/mobile/store/notificationStore.ts",
    "apps/mobile/store/offlineStore.ts",
    
    "apps/mobile/services/api.ts",
    "apps/mobile/services/auth.service.ts",
    "apps/mobile/services/student.service.ts",
    "apps/mobile/services/attendance.service.ts",
    "apps/mobile/services/homework.service.ts",
    "apps/mobile/services/notification.service.ts",
    "apps/mobile/services/insights.service.ts",
    
    "apps/mobile/constants/theme.ts",
    "apps/mobile/constants/routes.ts",
    "apps/mobile/constants/config.ts",
    
    "apps/mobile/assets/images/logo.png",
    "apps/mobile/assets/images/splash.png",
    "apps/mobile/assets/fonts/Poppins/placeholder.txt",
    
    "apps/mobile/__tests__/components/StudentCard.test.tsx",
    "apps/mobile/__tests__/hooks/useAuth.test.ts",
    
    "apps/mobile/app.json",
    "apps/mobile/eas.json",
    "apps/mobile/babel.config.js",
    "apps/mobile/package.json",

    "apps/web/app/layout.tsx",
    "apps/web/app/page.tsx",
    "apps/web/app/(auth)/login/page.tsx",
    "apps/web/app/(auth)/forgot-password/page.tsx",
    "apps/web/app/admin/layout.tsx",
    "apps/web/app/admin/page.tsx",
    
    "apps/web/app/admin/insights/page.tsx",
    "apps/web/app/admin/insights/at-risk/page.tsx",
    "apps/web/app/admin/insights/performance/page.tsx",
    "apps/web/app/admin/insights/fee-risk/page.tsx",
    "apps/web/app/admin/insights/teacher-activity/page.tsx",
    
    "apps/web/app/admin/students/page.tsx",
    "apps/web/app/admin/students/add/page.tsx",
    "apps/web/app/admin/students/[id]/page.tsx",
    "apps/web/app/admin/students/[id]/edit/page.tsx",
    "apps/web/app/admin/students/[id]/insights/page.tsx",
    "apps/web/app/admin/students/[id]/attendance/page.tsx",
    "apps/web/app/admin/students/[id]/fees/page.tsx",
    "apps/web/app/admin/students/[id]/results/page.tsx",
    
    "apps/web/app/admin/teachers/page.tsx",
    "apps/web/app/admin/teachers/add/page.tsx",
    "apps/web/app/admin/teachers/[id]/page.tsx",
    "apps/web/app/admin/teachers/[id]/edit/page.tsx",
    "apps/web/app/admin/teachers/[id]/insights/page.tsx",
    
    "apps/web/app/admin/users/page.tsx",
    "apps/web/app/admin/users/[id]/page.tsx",
    "apps/web/app/admin/attendance/page.tsx",
    "apps/web/app/admin/attendance/override/page.tsx",
    
    "apps/web/app/admin/fees/page.tsx",
    "apps/web/app/admin/fees/add/page.tsx",
    "apps/web/app/admin/fees/[id]/page.tsx",
    
    "apps/web/app/admin/gate-logs/page.tsx",
    "apps/web/app/admin/gate-logs/add/page.tsx",
    "apps/web/app/admin/announcements/page.tsx",
    "apps/web/app/admin/announcements/add/page.tsx",
    "apps/web/app/admin/timetable/page.tsx",
    
    "apps/web/app/admin/reports/page.tsx",
    "apps/web/app/admin/reports/attendance/page.tsx",
    "apps/web/app/admin/reports/fees/page.tsx",
    "apps/web/app/admin/reports/results/page.tsx",
    "apps/web/app/admin/audit-log/page.tsx",
    "apps/web/app/admin/settings/page.tsx",
    "apps/web/app/admin/settings/academic-year/page.tsx",
    "apps/web/app/admin/settings/grades/page.tsx",
    "apps/web/app/admin/settings/subjects/page.tsx",
    
    "apps/web/app/teacher/layout.tsx",
    "apps/web/app/teacher/page.tsx",
    "apps/web/app/teacher/insights/page.tsx",
    "apps/web/app/teacher/insights/class-performance/page.tsx",
    "apps/web/app/teacher/insights/submission-trends/page.tsx",
    
    "apps/web/app/teacher/homework/page.tsx",
    "apps/web/app/teacher/homework/[id]/page.tsx",
    "apps/web/app/teacher/homework/[id]/edit/page.tsx",
    "apps/web/app/teacher/attendance/page.tsx",
    "apps/web/app/teacher/attendance/history/page.tsx",
    "apps/web/app/teacher/assignments/page.tsx",
    "apps/web/app/teacher/assignments/add/page.tsx",
    "apps/web/app/teacher/assignments/[id]/page.tsx",
    "apps/web/app/teacher/assignments/[id]/grade/page.tsx",
    "apps/web/app/teacher/grades/page.tsx",
    "apps/web/app/teacher/grades/add/page.tsx",
    "apps/web/app/teacher/grades/[id]/page.tsx",
    "apps/web/app/teacher/announcements/page.tsx",
    "apps/web/app/teacher/announcements/add/page.tsx",
    "apps/web/app/teacher/meetings/page.tsx",
    "apps/web/app/teacher/meetings/schedule/page.tsx",
    "apps/web/app/teacher/timetable/page.tsx",
    "apps/web/app/teacher/profile/page.tsx",
    
    "apps/web/components/ui/Button.tsx",
    "apps/web/components/ui/Input.tsx",
    "apps/web/components/ui/Select.tsx",
    "apps/web/components/ui/Table.tsx",
    "apps/web/components/ui/Modal.tsx",
    "apps/web/components/ui/Drawer.tsx",
    "apps/web/components/ui/Badge.tsx",
    "apps/web/components/ui/Skeleton.tsx",
    "apps/web/components/ui/Pagination.tsx",
    "apps/web/components/ui/SearchBar.tsx",
    "apps/web/components/ui/DatePicker.tsx",
    "apps/web/components/ui/FileUpload.tsx",
    "apps/web/components/ui/ConfirmDialog.tsx",
    "apps/web/components/ui/Toast.tsx",
    "apps/web/components/ui/EmptyState.tsx",
    
    "apps/web/components/layout/AdminSidebar.tsx",
    "apps/web/components/layout/TeacherSidebar.tsx",
    "apps/web/components/layout/TopBar.tsx",
    "apps/web/components/layout/PageHeader.tsx",
    "apps/web/components/layout/MobileNav.tsx",
    
    "apps/web/components/dashboard/StatCard.tsx",
    "apps/web/components/dashboard/RecentActivity.tsx",
    "apps/web/components/dashboard/QuickActions.tsx",
    "apps/web/components/dashboard/AlertBanner.tsx",
    
    "apps/web/components/ai/InsightCard.tsx",
    "apps/web/components/ai/RiskBadge.tsx",
    "apps/web/components/ai/AtRiskTable.tsx",
    "apps/web/components/ai/PerformanceHeatmap.tsx",
    "apps/web/components/ai/GradeTrendChart.tsx",
    "apps/web/components/ai/AttendancePatternChart.tsx",
    "apps/web/components/ai/SubjectComparisonChart.tsx",
    "apps/web/components/ai/FeeRiskList.tsx",
    "apps/web/components/ai/TeacherActivityScore.tsx",
    "apps/web/components/ai/InsightSummaryPanel.tsx",
    "apps/web/components/ai/AnomalyAlert.tsx",
    
    "apps/web/components/students/StudentTable.tsx",
    "apps/web/components/students/StudentFilters.tsx",
    "apps/web/components/students/StudentAvatar.tsx",
    
    "apps/web/components/forms/AddStudentForm.tsx",
    "apps/web/components/forms/FamilyInfoForm.tsx",
    "apps/web/components/forms/AddTeacherForm.tsx",
    "apps/web/components/forms/HomeworkForm.tsx",
    "apps/web/components/forms/AttendanceMarker.tsx",
    "apps/web/components/forms/BulkAttendanceRow.tsx",
    "apps/web/components/forms/GradeEntryForm.tsx",
    "apps/web/components/forms/BulkGradeTable.tsx",
    "apps/web/components/forms/FeeForm.tsx",
    "apps/web/components/forms/BulkFeeForm.tsx",
    "apps/web/components/forms/AnnouncementForm.tsx",
    
    "apps/web/components/charts/AttendanceChart.tsx",
    "apps/web/components/charts/FeeCollectionChart.tsx",
    "apps/web/components/charts/GradeDistributionChart.tsx",
    "apps/web/components/charts/GateActivityChart.tsx",
    
    "apps/web/components/reports/ExportButton.tsx",
    "apps/web/components/reports/ReportFilters.tsx",
    
    "apps/web/hooks/useAuth.ts",
    "apps/web/hooks/useStudents.ts",
    "apps/web/hooks/useTeachers.ts",
    "apps/web/hooks/useAttendance.ts",
    "apps/web/hooks/useFees.ts",
    "apps/web/hooks/useGrades.ts",
    "apps/web/hooks/usePagination.ts",
    "apps/web/hooks/useDebounce.ts",
    "apps/web/hooks/useExport.ts",
    "apps/web/hooks/useInsights.ts",
    
    "apps/web/store/authStore.ts",
    "apps/web/lib/api.ts",
    "apps/web/lib/queryClient.ts",
    "apps/web/middleware.ts",
    "apps/web/next.config.js",
    "apps/web/tailwind.config.ts",
    "apps/web/tsconfig.json",
    "apps/web/package.json",
    
    "apps/server/src/routes/v1/index.ts",
    "apps/server/src/routes/v1/auth.routes.ts",
    "apps/server/src/routes/v1/student.routes.ts",
    "apps/server/src/routes/v1/teacher.routes.ts",
    "apps/server/src/routes/v1/attendance.routes.ts",
    "apps/server/src/routes/v1/homework.routes.ts",
    "apps/server/src/routes/v1/assignment.routes.ts",
    "apps/server/src/routes/v1/exam.routes.ts",
    "apps/server/src/routes/v1/fee.routes.ts",
    "apps/server/src/routes/v1/announcement.routes.ts",
    "apps/server/src/routes/v1/gate.routes.ts",
    "apps/server/src/routes/v1/meeting.routes.ts",
    "apps/server/src/routes/v1/application.routes.ts",
    "apps/server/src/routes/v1/timetable.routes.ts",
    "apps/server/src/routes/v1/report.routes.ts",
    "apps/server/src/routes/v1/audit.routes.ts",
    "apps/server/src/routes/v1/settings.routes.ts",
    "apps/server/src/routes/v1/insights.routes.ts",
    "apps/server/src/routes/health.routes.ts",
    
    "apps/server/src/controllers/auth.controller.ts",
    "apps/server/src/controllers/student.controller.ts",
    "apps/server/src/controllers/teacher.controller.ts",
    "apps/server/src/controllers/attendance.controller.ts",
    "apps/server/src/controllers/homework.controller.ts",
    "apps/server/src/controllers/assignment.controller.ts",
    "apps/server/src/controllers/exam.controller.ts",
    "apps/server/src/controllers/fee.controller.ts",
    "apps/server/src/controllers/announcement.controller.ts",
    "apps/server/src/controllers/gate.controller.ts",
    "apps/server/src/controllers/meeting.controller.ts",
    "apps/server/src/controllers/application.controller.ts",
    "apps/server/src/controllers/timetable.controller.ts",
    "apps/server/src/controllers/report.controller.ts",
    "apps/server/src/controllers/audit.controller.ts",
    "apps/server/src/controllers/settings.controller.ts",
    "apps/server/src/controllers/insights.controller.ts",
    
    "apps/server/src/services/auth.service.ts",
    "apps/server/src/services/student.service.ts",
    "apps/server/src/services/teacher.service.ts",
    "apps/server/src/services/attendance.service.ts",
    "apps/server/src/services/homework.service.ts",
    "apps/server/src/services/assignment.service.ts",
    "apps/server/src/services/exam.service.ts",
    "apps/server/src/services/fee.service.ts",
    "apps/server/src/services/announcement.service.ts",
    "apps/server/src/services/gate.service.ts",
    "apps/server/src/services/meeting.service.ts",
    "apps/server/src/services/application.service.ts",
    "apps/server/src/services/timetable.service.ts",
    "apps/server/src/services/report.service.ts",
    "apps/server/src/services/pdf.service.ts",
    "apps/server/src/services/cache.service.ts",
    "apps/server/src/services/notification.service.ts",
    "apps/server/src/services/upload.service.ts",
    
    "apps/server/src/ai/index.ts",
    "apps/server/src/ai/engine/gradePredictor.ts",
    "apps/server/src/ai/engine/attendanceRisk.ts",
    "apps/server/src/ai/engine/performanceScorer.ts",
    "apps/server/src/ai/engine/subjectWeakness.ts",
    "apps/server/src/ai/engine/feeRiskScorer.ts",
    "apps/server/src/ai/engine/anomalyDetector.ts",
    "apps/server/src/ai/engine/teacherActivity.ts",
    "apps/server/src/ai/engine/classComparison.ts",
    
    "apps/server/src/ai/prompts/studentSummary.prompt.ts",
    "apps/server/src/ai/prompts/attendanceNarrative.prompt.ts",
    "apps/server/src/ai/prompts/gradeNarrative.prompt.ts",
    "apps/server/src/ai/prompts/teacherInsight.prompt.ts",
    "apps/server/src/ai/prompts/adminOverview.prompt.ts",
    "apps/server/src/ai/prompts/weeklyDigest.prompt.ts",
    
    "apps/server/src/ai/pipelines/studentInsightPipeline.ts",
    "apps/server/src/ai/pipelines/classInsightPipeline.ts",
    "apps/server/src/ai/pipelines/schoolInsightPipeline.ts",
    "apps/server/src/ai/pipelines/teacherInsightPipeline.ts",
    
    "apps/server/src/ai/formatters/insightFormatter.ts",
    "apps/server/src/ai/formatters/responseParser.ts",
    
    "apps/server/src/ai/cache/insightCache.ts",
    
    "apps/server/src/middleware/auth.middleware.ts",
    "apps/server/src/middleware/role.middleware.ts",
    "apps/server/src/middleware/validate.middleware.ts",
    "apps/server/src/middleware/rateLimit.middleware.ts",
    "apps/server/src/middleware/audit.middleware.ts",
    "apps/server/src/middleware/cors.middleware.ts",
    "apps/server/src/middleware/helmet.middleware.ts",
    "apps/server/src/middleware/logger.middleware.ts",
    
    "apps/server/src/jobs/scheduler.ts",
    "apps/server/src/jobs/dailyAttendanceAlert.job.ts",
    "apps/server/src/jobs/feeReminder.job.ts",
    "apps/server/src/jobs/dbBackup.job.ts",
    "apps/server/src/jobs/weeklyInsightDigest.job.ts",
    "apps/server/src/jobs/anomalyScan.job.ts",
    
    "apps/server/src/events/eventBus.ts",
    "apps/server/src/events/student.events.ts",
    "apps/server/src/events/fee.events.ts",
    "apps/server/src/events/insight.events.ts",
    
    "apps/server/src/prisma/client.ts",
    "apps/server/src/redis/client.ts",
    "apps/server/src/storage/cloudinary.ts",
    
    "apps/server/src/utils/jwt.ts",
    "apps/server/src/utils/bcrypt.ts",
    "apps/server/src/utils/response.ts",
    "apps/server/src/utils/paginate.ts",
    "apps/server/src/utils/rollNumber.ts",
    "apps/server/src/utils/gradeCalc.ts",
    
    "apps/server/src/types/express.d.ts",
    "apps/server/src/types/environment.d.ts",
    "apps/server/src/types/insight.types.ts",
    
    "apps/server/src/config/env.ts",
    "apps/server/src/config/cors.ts",
    "apps/server/src/config/rateLimit.ts",
    "apps/server/src/config/ai.ts",
    
    "apps/server/src/app.ts",
    
    "apps/server/prisma/schema.prisma",
    "apps/server/prisma/migrations/placeholder.txt",
    "apps/server/prisma/seed/index.ts",
    "apps/server/prisma/seed/users.seed.ts",
    "apps/server/prisma/seed/students.seed.ts",
    "apps/server/prisma/seed/teachers.seed.ts",
    "apps/server/prisma/seed/attendance.seed.ts",
    "apps/server/prisma/seed/fees.seed.ts",
    "apps/server/prisma/seed/exams.seed.ts",
    
    "apps/server/tests/unit/services/auth.service.test.ts",
    "apps/server/tests/unit/services/student.service.test.ts",
    "apps/server/tests/unit/services/fee.service.test.ts",
    "apps/server/tests/unit/services/gradeCalc.test.ts",
    
    "apps/server/tests/unit/ai/gradePredictor.test.ts",
    "apps/server/tests/unit/ai/attendanceRisk.test.ts",
    "apps/server/tests/unit/ai/anomalyDetector.test.ts",
    "apps/server/tests/unit/ai/feeRiskScorer.test.ts",
    
    "apps/server/tests/unit/utils/rollNumber.test.ts",
    "apps/server/tests/unit/utils/paginate.test.ts",
    
    "apps/server/tests/integration/auth.test.ts",
    "apps/server/tests/integration/student.test.ts",
    "apps/server/tests/integration/attendance.test.ts",
    "apps/server/tests/integration/fee.test.ts",
    "apps/server/tests/integration/insights.test.ts",
    
    "apps/server/tests/setup.ts",
    "apps/server/tsconfig.json",
    "apps/server/nodemon.json",
    "apps/server/package.json",
    
    "packages/types/src/auth.types.ts",
    "packages/types/src/user.types.ts",
    "packages/types/src/student.types.ts",
    "packages/types/src/teacher.types.ts",
    "packages/types/src/attendance.types.ts",
    "packages/types/src/homework.types.ts",
    "packages/types/src/assignment.types.ts",
    "packages/types/src/exam.types.ts",
    "packages/types/src/fee.types.ts",
    "packages/types/src/announcement.types.ts",
    "packages/types/src/gate.types.ts",
    "packages/types/src/meeting.types.ts",
    "packages/types/src/application.types.ts",
    "packages/types/src/timetable.types.ts",
    "packages/types/src/report.types.ts",
    "packages/types/src/api.types.ts",
    "packages/types/src/insight.types.ts",
    "packages/types/src/index.ts",
    "packages/types/tsconfig.json",
    "packages/types/package.json",
    
    "packages/validators/src/auth.schema.ts",
    "packages/validators/src/student.schema.ts",
    "packages/validators/src/teacher.schema.ts",
    "packages/validators/src/attendance.schema.ts",
    "packages/validators/src/homework.schema.ts",
    "packages/validators/src/assignment.schema.ts",
    "packages/validators/src/exam.schema.ts",
    "packages/validators/src/fee.schema.ts",
    "packages/validators/src/announcement.schema.ts",
    "packages/validators/src/gate.schema.ts",
    "packages/validators/src/meeting.schema.ts",
    "packages/validators/src/application.schema.ts",
    "packages/validators/src/timetable.schema.ts",
    "packages/validators/src/index.ts",
    "packages/validators/tsconfig.json",
    "packages/validators/package.json",
    
    "packages/utils/src/formatDate.ts",
    "packages/utils/src/formatCurrency.ts",
    "packages/utils/src/calcGrade.ts",
    "packages/utils/src/calcAttendancePercent.ts",
    "packages/utils/src/genRollNumber.ts",
    "packages/utils/src/truncateText.ts",
    "packages/utils/src/groupBy.ts",
    "packages/utils/src/index.ts",
    "packages/utils/tsconfig.json",
    "packages/utils/package.json",
    
    "packages/ui/src/colors.ts",
    "packages/ui/src/spacing.ts",
    "packages/ui/src/typography.ts",
    "packages/ui/src/index.ts",
    "packages/ui/package.json",
    
    "infrastructure/docker/Dockerfile.server",
    "infrastructure/docker/Dockerfile.web",
    "infrastructure/docker/.dockerignore",
    "infrastructure/nginx/nginx.conf",
    "infrastructure/scripts/setup.sh",
    "infrastructure/scripts/reset-db.sh",
    "infrastructure/scripts/generate-env.sh",
    
    "docs/architecture.md",
    "docs/ai-insights.md",
    "docs/api/auth.md",
    "docs/api/students.md",
    "docs/api/attendance.md",
    "docs/api/fees.md",
    "docs/api/insights.md",
    "docs/deployment.md",
    "docs/database-schema.md",
    "docs/contributing.md",
    
    "docker-compose.yml",
    "docker-compose.prod.yml",
    ".env.example",
    ".env.test",
    ".gitignore",
    ".eslintrc.js",
    ".prettierrc",
    "tsconfig.base.json",
    "pnpm-workspace.yaml",
    "turbo.json",
    "README.md"
]

for file in files:
    path = os.path.join("C:\\Users\\Admin\\Documents\\GitHub\\Edu-portal", file.replace('/', '\\'))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if not os.path.exists(path):
        open(path, 'w').close()
